// <auto-generated />
namespace Test
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Data;
    using BC_SalesOrder;

    /// <summary>
    /// Main
    /// </summary>
    public class Program
    {
        public static void Main(string[] args)
        {
            ListaSalesOrder();
        }
        
        /// <summary>
        /// Listado de Sales Order
        /// </summary>
        private static void ListaSalesOrder()
        {

            ServicioSalesOrder.WS_SalesOrderClient serSalesOrder = new ServicioSalesOrder.WS_SalesOrderClient();
            serSalesOrder.GetSalesOrder("C");
            serSalesOrder.Close();


            //serSalesOrder.Confirmation("3400000", "00000012", "00017", "SR", "i");

            //clsSalesOrder SalesOrder = new clsSalesOrder();
            //int s = SalesOrder.Get_Cia("20901061");
            //Console.Write(s);
            //Console.ReadLine(); 

            //clsSalesOrder SalesOrder = new clsSalesOrder();
            //int s = SalesOrder.Get_ScrValida(2200976);
            //Console.Write(s);
            //Console.ReadLine(); 


        }
    }
}
