//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServicioSalesOrder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.praxair.com.co/SalesOrder", ConfigurationName="ServicioSalesOrder.IWS_SalesOrder")]
    public interface IWS_SalesOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/GetSalesOrder", ReplyAction="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/GetSalesOrderResponse")]
        void GetSalesOrder(string InterfaceStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/Confirmation", ReplyAction="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/ConfirmationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WCF_SalesOrder.clsResponse), Action="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/ConfirmationInternalException" +
            "", Name="InternalException")]
        WCF_SalesOrder.clsResponse[] Confirmation(string mcu, string legacyConsecutive, string legacyPrefix, string dcto, string interfaceStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWS_SalesOrderChannel : Test.ServicioSalesOrder.IWS_SalesOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SalesOrderClient : System.ServiceModel.ClientBase<Test.ServicioSalesOrder.IWS_SalesOrder>, Test.ServicioSalesOrder.IWS_SalesOrder {
        
        public WS_SalesOrderClient() {
        }
        
        public WS_SalesOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SalesOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SalesOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SalesOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetSalesOrder(string InterfaceStatus) {
            base.Channel.GetSalesOrder(InterfaceStatus);
        }
        
        public WCF_SalesOrder.clsResponse[] Confirmation(string mcu, string legacyConsecutive, string legacyPrefix, string dcto, string interfaceStatus) {
            return base.Channel.Confirmation(mcu, legacyConsecutive, legacyPrefix, dcto, interfaceStatus);
        }
    }
}
