//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebDesicionTable.ServicioAutenticacion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgenciasUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmpresasUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback GruposUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback DivisionesUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModulosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BaseEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback datosUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback usuarioFuncionOperationCompleted;
        
        private System.Threading.SendOrPostCallback usuarioValidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestraCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback MaestraCorreosGeneralOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParametrosEncCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParametrosDetCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback valorParametrosDetCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback DatosCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ejecutaProcedimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EncriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback DesEncriptarOperationCompleted;
        
        private System.Threading.SendOrPostCallback descripcionGrupoOperationCompleted;
        
        private System.Threading.SendOrPostCallback descripcionEmpresaOperationCompleted;
        
        private System.Threading.SendOrPostCallback descripcionAgenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback OlvidoContrasenaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CambioContrasenaOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarMaestraCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarMaestraCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarMaestraCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDetalleCorreosOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarDetalleCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback valorCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaisOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::WebDesicionTable.Properties.Settings.Default.WebDesicionTable_ServicioAutenticacion_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgenciasUsuarioCompletedEventHandler AgenciasUsuarioCompleted;
        
        /// <remarks/>
        public event EmpresasUsuarioCompletedEventHandler EmpresasUsuarioCompleted;
        
        /// <remarks/>
        public event GruposUsuarioCompletedEventHandler GruposUsuarioCompleted;
        
        /// <remarks/>
        public event DivisionesUsuarioCompletedEventHandler DivisionesUsuarioCompleted;
        
        /// <remarks/>
        public event ModulosUsuarioCompletedEventHandler ModulosUsuarioCompleted;
        
        /// <remarks/>
        public event BaseEmpresaCompletedEventHandler BaseEmpresaCompleted;
        
        /// <remarks/>
        public event datosUsuarioCompletedEventHandler datosUsuarioCompleted;
        
        /// <remarks/>
        public event usuarioFuncionCompletedEventHandler usuarioFuncionCompleted;
        
        /// <remarks/>
        public event usuarioValidoCompletedEventHandler usuarioValidoCompleted;
        
        /// <remarks/>
        public event MaestraCorreosCompletedEventHandler MaestraCorreosCompleted;
        
        /// <remarks/>
        public event MaestraCorreosGeneralCompletedEventHandler MaestraCorreosGeneralCompleted;
        
        /// <remarks/>
        public event ParametrosEncCorreosCompletedEventHandler ParametrosEncCorreosCompleted;
        
        /// <remarks/>
        public event ParametrosDetCorreosCompletedEventHandler ParametrosDetCorreosCompleted;
        
        /// <remarks/>
        public event valorParametrosDetCorreosCompletedEventHandler valorParametrosDetCorreosCompleted;
        
        /// <remarks/>
        public event DatosCorreoCompletedEventHandler DatosCorreoCompleted;
        
        /// <remarks/>
        public event ejecutaProcedimientoCompletedEventHandler ejecutaProcedimientoCompleted;
        
        /// <remarks/>
        public event EncriptarCompletedEventHandler EncriptarCompleted;
        
        /// <remarks/>
        public event DesEncriptarCompletedEventHandler DesEncriptarCompleted;
        
        /// <remarks/>
        public event descripcionGrupoCompletedEventHandler descripcionGrupoCompleted;
        
        /// <remarks/>
        public event descripcionEmpresaCompletedEventHandler descripcionEmpresaCompleted;
        
        /// <remarks/>
        public event descripcionAgenciaCompletedEventHandler descripcionAgenciaCompleted;
        
        /// <remarks/>
        public event OlvidoContrasenaCompletedEventHandler OlvidoContrasenaCompleted;
        
        /// <remarks/>
        public event CambioContrasenaCompletedEventHandler CambioContrasenaCompleted;
        
        /// <remarks/>
        public event InsertarMaestraCorreosCompletedEventHandler InsertarMaestraCorreosCompleted;
        
        /// <remarks/>
        public event ModificarMaestraCorreosCompletedEventHandler ModificarMaestraCorreosCompleted;
        
        /// <remarks/>
        public event EliminarMaestraCorreosCompletedEventHandler EliminarMaestraCorreosCompleted;
        
        /// <remarks/>
        public event EliminarDetalleCorreosCompletedEventHandler EliminarDetalleCorreosCompleted;
        
        /// <remarks/>
        public event InsertarDetalleCorreoCompletedEventHandler InsertarDetalleCorreoCompleted;
        
        /// <remarks/>
        public event valorCacheCompletedEventHandler valorCacheCompleted;
        
        /// <remarks/>
        public event PaisCompletedEventHandler PaisCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgenciasUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet AgenciasUsuario(int p_Usrid, int p_Grupo, int p_empid) {
            object[] results = this.Invoke("AgenciasUsuario", new object[] {
                        p_Usrid,
                        p_Grupo,
                        p_empid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void AgenciasUsuarioAsync(int p_Usrid, int p_Grupo, int p_empid) {
            this.AgenciasUsuarioAsync(p_Usrid, p_Grupo, p_empid, null);
        }
        
        /// <remarks/>
        public void AgenciasUsuarioAsync(int p_Usrid, int p_Grupo, int p_empid, object userState) {
            if ((this.AgenciasUsuarioOperationCompleted == null)) {
                this.AgenciasUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgenciasUsuarioOperationCompleted);
            }
            this.InvokeAsync("AgenciasUsuario", new object[] {
                        p_Usrid,
                        p_Grupo,
                        p_empid}, this.AgenciasUsuarioOperationCompleted, userState);
        }
        
        private void OnAgenciasUsuarioOperationCompleted(object arg) {
            if ((this.AgenciasUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgenciasUsuarioCompleted(this, new AgenciasUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EmpresasUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet EmpresasUsuario(int p_Usrid, int p_Grupo) {
            object[] results = this.Invoke("EmpresasUsuario", new object[] {
                        p_Usrid,
                        p_Grupo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void EmpresasUsuarioAsync(int p_Usrid, int p_Grupo) {
            this.EmpresasUsuarioAsync(p_Usrid, p_Grupo, null);
        }
        
        /// <remarks/>
        public void EmpresasUsuarioAsync(int p_Usrid, int p_Grupo, object userState) {
            if ((this.EmpresasUsuarioOperationCompleted == null)) {
                this.EmpresasUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmpresasUsuarioOperationCompleted);
            }
            this.InvokeAsync("EmpresasUsuario", new object[] {
                        p_Usrid,
                        p_Grupo}, this.EmpresasUsuarioOperationCompleted, userState);
        }
        
        private void OnEmpresasUsuarioOperationCompleted(object arg) {
            if ((this.EmpresasUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmpresasUsuarioCompleted(this, new EmpresasUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GruposUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GruposUsuario(int p_Usrid) {
            object[] results = this.Invoke("GruposUsuario", new object[] {
                        p_Usrid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GruposUsuarioAsync(int p_Usrid) {
            this.GruposUsuarioAsync(p_Usrid, null);
        }
        
        /// <remarks/>
        public void GruposUsuarioAsync(int p_Usrid, object userState) {
            if ((this.GruposUsuarioOperationCompleted == null)) {
                this.GruposUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGruposUsuarioOperationCompleted);
            }
            this.InvokeAsync("GruposUsuario", new object[] {
                        p_Usrid}, this.GruposUsuarioOperationCompleted, userState);
        }
        
        private void OnGruposUsuarioOperationCompleted(object arg) {
            if ((this.GruposUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GruposUsuarioCompleted(this, new GruposUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DivisionesUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DivisionesUsuario(int p_Usrid, int p_Grupo, int p_Empid) {
            object[] results = this.Invoke("DivisionesUsuario", new object[] {
                        p_Usrid,
                        p_Grupo,
                        p_Empid});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DivisionesUsuarioAsync(int p_Usrid, int p_Grupo, int p_Empid) {
            this.DivisionesUsuarioAsync(p_Usrid, p_Grupo, p_Empid, null);
        }
        
        /// <remarks/>
        public void DivisionesUsuarioAsync(int p_Usrid, int p_Grupo, int p_Empid, object userState) {
            if ((this.DivisionesUsuarioOperationCompleted == null)) {
                this.DivisionesUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDivisionesUsuarioOperationCompleted);
            }
            this.InvokeAsync("DivisionesUsuario", new object[] {
                        p_Usrid,
                        p_Grupo,
                        p_Empid}, this.DivisionesUsuarioOperationCompleted, userState);
        }
        
        private void OnDivisionesUsuarioOperationCompleted(object arg) {
            if ((this.DivisionesUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DivisionesUsuarioCompleted(this, new DivisionesUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModulosUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ModulosUsuario(int p_Usrid, int p_Padre) {
            object[] results = this.Invoke("ModulosUsuario", new object[] {
                        p_Usrid,
                        p_Padre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ModulosUsuarioAsync(int p_Usrid, int p_Padre) {
            this.ModulosUsuarioAsync(p_Usrid, p_Padre, null);
        }
        
        /// <remarks/>
        public void ModulosUsuarioAsync(int p_Usrid, int p_Padre, object userState) {
            if ((this.ModulosUsuarioOperationCompleted == null)) {
                this.ModulosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModulosUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModulosUsuario", new object[] {
                        p_Usrid,
                        p_Padre}, this.ModulosUsuarioOperationCompleted, userState);
        }
        
        private void OnModulosUsuarioOperationCompleted(object arg) {
            if ((this.ModulosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModulosUsuarioCompleted(this, new ModulosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BaseEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BaseEmpresa(int p_Grupo, int p_Empresa) {
            object[] results = this.Invoke("BaseEmpresa", new object[] {
                        p_Grupo,
                        p_Empresa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BaseEmpresaAsync(int p_Grupo, int p_Empresa) {
            this.BaseEmpresaAsync(p_Grupo, p_Empresa, null);
        }
        
        /// <remarks/>
        public void BaseEmpresaAsync(int p_Grupo, int p_Empresa, object userState) {
            if ((this.BaseEmpresaOperationCompleted == null)) {
                this.BaseEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBaseEmpresaOperationCompleted);
            }
            this.InvokeAsync("BaseEmpresa", new object[] {
                        p_Grupo,
                        p_Empresa}, this.BaseEmpresaOperationCompleted, userState);
        }
        
        private void OnBaseEmpresaOperationCompleted(object arg) {
            if ((this.BaseEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BaseEmpresaCompleted(this, new BaseEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/datosUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string datosUsuario(string p_Usrnmb, int p_TipoRetorno) {
            object[] results = this.Invoke("datosUsuario", new object[] {
                        p_Usrnmb,
                        p_TipoRetorno});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void datosUsuarioAsync(string p_Usrnmb, int p_TipoRetorno) {
            this.datosUsuarioAsync(p_Usrnmb, p_TipoRetorno, null);
        }
        
        /// <remarks/>
        public void datosUsuarioAsync(string p_Usrnmb, int p_TipoRetorno, object userState) {
            if ((this.datosUsuarioOperationCompleted == null)) {
                this.datosUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OndatosUsuarioOperationCompleted);
            }
            this.InvokeAsync("datosUsuario", new object[] {
                        p_Usrnmb,
                        p_TipoRetorno}, this.datosUsuarioOperationCompleted, userState);
        }
        
        private void OndatosUsuarioOperationCompleted(object arg) {
            if ((this.datosUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.datosUsuarioCompleted(this, new datosUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/usuarioFuncion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string usuarioFuncion(int p_usrid, string p_Funcion) {
            object[] results = this.Invoke("usuarioFuncion", new object[] {
                        p_usrid,
                        p_Funcion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void usuarioFuncionAsync(int p_usrid, string p_Funcion) {
            this.usuarioFuncionAsync(p_usrid, p_Funcion, null);
        }
        
        /// <remarks/>
        public void usuarioFuncionAsync(int p_usrid, string p_Funcion, object userState) {
            if ((this.usuarioFuncionOperationCompleted == null)) {
                this.usuarioFuncionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnusuarioFuncionOperationCompleted);
            }
            this.InvokeAsync("usuarioFuncion", new object[] {
                        p_usrid,
                        p_Funcion}, this.usuarioFuncionOperationCompleted, userState);
        }
        
        private void OnusuarioFuncionOperationCompleted(object arg) {
            if ((this.usuarioFuncionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.usuarioFuncionCompleted(this, new usuarioFuncionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/usuarioValido", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string usuarioValido(string p_Usrnmb, string p_Password) {
            object[] results = this.Invoke("usuarioValido", new object[] {
                        p_Usrnmb,
                        p_Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void usuarioValidoAsync(string p_Usrnmb, string p_Password) {
            this.usuarioValidoAsync(p_Usrnmb, p_Password, null);
        }
        
        /// <remarks/>
        public void usuarioValidoAsync(string p_Usrnmb, string p_Password, object userState) {
            if ((this.usuarioValidoOperationCompleted == null)) {
                this.usuarioValidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnusuarioValidoOperationCompleted);
            }
            this.InvokeAsync("usuarioValido", new object[] {
                        p_Usrnmb,
                        p_Password}, this.usuarioValidoOperationCompleted, userState);
        }
        
        private void OnusuarioValidoOperationCompleted(object arg) {
            if ((this.usuarioValidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.usuarioValidoCompleted(this, new usuarioValidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MaestraCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MaestraCorreos() {
            object[] results = this.Invoke("MaestraCorreos", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MaestraCorreosAsync() {
            this.MaestraCorreosAsync(null);
        }
        
        /// <remarks/>
        public void MaestraCorreosAsync(object userState) {
            if ((this.MaestraCorreosOperationCompleted == null)) {
                this.MaestraCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestraCorreosOperationCompleted);
            }
            this.InvokeAsync("MaestraCorreos", new object[0], this.MaestraCorreosOperationCompleted, userState);
        }
        
        private void OnMaestraCorreosOperationCompleted(object arg) {
            if ((this.MaestraCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestraCorreosCompleted(this, new MaestraCorreosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MaestraCorreosGeneral", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet MaestraCorreosGeneral() {
            object[] results = this.Invoke("MaestraCorreosGeneral", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void MaestraCorreosGeneralAsync() {
            this.MaestraCorreosGeneralAsync(null);
        }
        
        /// <remarks/>
        public void MaestraCorreosGeneralAsync(object userState) {
            if ((this.MaestraCorreosGeneralOperationCompleted == null)) {
                this.MaestraCorreosGeneralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMaestraCorreosGeneralOperationCompleted);
            }
            this.InvokeAsync("MaestraCorreosGeneral", new object[0], this.MaestraCorreosGeneralOperationCompleted, userState);
        }
        
        private void OnMaestraCorreosGeneralOperationCompleted(object arg) {
            if ((this.MaestraCorreosGeneralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MaestraCorreosGeneralCompleted(this, new MaestraCorreosGeneralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParametrosEncCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ParametrosEncCorreos(string p_NombreServicio, int p_IdCorreo) {
            object[] results = this.Invoke("ParametrosEncCorreos", new object[] {
                        p_NombreServicio,
                        p_IdCorreo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ParametrosEncCorreosAsync(string p_NombreServicio, int p_IdCorreo) {
            this.ParametrosEncCorreosAsync(p_NombreServicio, p_IdCorreo, null);
        }
        
        /// <remarks/>
        public void ParametrosEncCorreosAsync(string p_NombreServicio, int p_IdCorreo, object userState) {
            if ((this.ParametrosEncCorreosOperationCompleted == null)) {
                this.ParametrosEncCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParametrosEncCorreosOperationCompleted);
            }
            this.InvokeAsync("ParametrosEncCorreos", new object[] {
                        p_NombreServicio,
                        p_IdCorreo}, this.ParametrosEncCorreosOperationCompleted, userState);
        }
        
        private void OnParametrosEncCorreosOperationCompleted(object arg) {
            if ((this.ParametrosEncCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParametrosEncCorreosCompleted(this, new ParametrosEncCorreosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ParametrosDetCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ParametrosDetCorreos(string p_NombreServicio, int p_IdCorreo, string p_Parametro) {
            object[] results = this.Invoke("ParametrosDetCorreos", new object[] {
                        p_NombreServicio,
                        p_IdCorreo,
                        p_Parametro});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ParametrosDetCorreosAsync(string p_NombreServicio, int p_IdCorreo, string p_Parametro) {
            this.ParametrosDetCorreosAsync(p_NombreServicio, p_IdCorreo, p_Parametro, null);
        }
        
        /// <remarks/>
        public void ParametrosDetCorreosAsync(string p_NombreServicio, int p_IdCorreo, string p_Parametro, object userState) {
            if ((this.ParametrosDetCorreosOperationCompleted == null)) {
                this.ParametrosDetCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParametrosDetCorreosOperationCompleted);
            }
            this.InvokeAsync("ParametrosDetCorreos", new object[] {
                        p_NombreServicio,
                        p_IdCorreo,
                        p_Parametro}, this.ParametrosDetCorreosOperationCompleted, userState);
        }
        
        private void OnParametrosDetCorreosOperationCompleted(object arg) {
            if ((this.ParametrosDetCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParametrosDetCorreosCompleted(this, new ParametrosDetCorreosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/valorParametrosDetCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string valorParametrosDetCorreos(string p_NombreServicio, int p_IdCorreo, string p_Parametro) {
            object[] results = this.Invoke("valorParametrosDetCorreos", new object[] {
                        p_NombreServicio,
                        p_IdCorreo,
                        p_Parametro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void valorParametrosDetCorreosAsync(string p_NombreServicio, int p_IdCorreo, string p_Parametro) {
            this.valorParametrosDetCorreosAsync(p_NombreServicio, p_IdCorreo, p_Parametro, null);
        }
        
        /// <remarks/>
        public void valorParametrosDetCorreosAsync(string p_NombreServicio, int p_IdCorreo, string p_Parametro, object userState) {
            if ((this.valorParametrosDetCorreosOperationCompleted == null)) {
                this.valorParametrosDetCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalorParametrosDetCorreosOperationCompleted);
            }
            this.InvokeAsync("valorParametrosDetCorreos", new object[] {
                        p_NombreServicio,
                        p_IdCorreo,
                        p_Parametro}, this.valorParametrosDetCorreosOperationCompleted, userState);
        }
        
        private void OnvalorParametrosDetCorreosOperationCompleted(object arg) {
            if ((this.valorParametrosDetCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.valorParametrosDetCorreosCompleted(this, new valorParametrosDetCorreosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DatosCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet DatosCorreo(string p_NombreServicio, int p_IdCorreo) {
            object[] results = this.Invoke("DatosCorreo", new object[] {
                        p_NombreServicio,
                        p_IdCorreo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void DatosCorreoAsync(string p_NombreServicio, int p_IdCorreo) {
            this.DatosCorreoAsync(p_NombreServicio, p_IdCorreo, null);
        }
        
        /// <remarks/>
        public void DatosCorreoAsync(string p_NombreServicio, int p_IdCorreo, object userState) {
            if ((this.DatosCorreoOperationCompleted == null)) {
                this.DatosCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDatosCorreoOperationCompleted);
            }
            this.InvokeAsync("DatosCorreo", new object[] {
                        p_NombreServicio,
                        p_IdCorreo}, this.DatosCorreoOperationCompleted, userState);
        }
        
        private void OnDatosCorreoOperationCompleted(object arg) {
            if ((this.DatosCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DatosCorreoCompleted(this, new DatosCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ejecutaProcedimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ejecutaProcedimiento(string p_NombreServicio, string p_Procedimiento) {
            this.Invoke("ejecutaProcedimiento", new object[] {
                        p_NombreServicio,
                        p_Procedimiento});
        }
        
        /// <remarks/>
        public void ejecutaProcedimientoAsync(string p_NombreServicio, string p_Procedimiento) {
            this.ejecutaProcedimientoAsync(p_NombreServicio, p_Procedimiento, null);
        }
        
        /// <remarks/>
        public void ejecutaProcedimientoAsync(string p_NombreServicio, string p_Procedimiento, object userState) {
            if ((this.ejecutaProcedimientoOperationCompleted == null)) {
                this.ejecutaProcedimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnejecutaProcedimientoOperationCompleted);
            }
            this.InvokeAsync("ejecutaProcedimiento", new object[] {
                        p_NombreServicio,
                        p_Procedimiento}, this.ejecutaProcedimientoOperationCompleted, userState);
        }
        
        private void OnejecutaProcedimientoOperationCompleted(object arg) {
            if ((this.ejecutaProcedimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ejecutaProcedimientoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Encriptar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Encriptar(string p_Cadena, int p_Opc) {
            object[] results = this.Invoke("Encriptar", new object[] {
                        p_Cadena,
                        p_Opc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncriptarAsync(string p_Cadena, int p_Opc) {
            this.EncriptarAsync(p_Cadena, p_Opc, null);
        }
        
        /// <remarks/>
        public void EncriptarAsync(string p_Cadena, int p_Opc, object userState) {
            if ((this.EncriptarOperationCompleted == null)) {
                this.EncriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncriptarOperationCompleted);
            }
            this.InvokeAsync("Encriptar", new object[] {
                        p_Cadena,
                        p_Opc}, this.EncriptarOperationCompleted, userState);
        }
        
        private void OnEncriptarOperationCompleted(object arg) {
            if ((this.EncriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncriptarCompleted(this, new EncriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DesEncriptar", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DesEncriptar(string p_Cadena, int p_Opc) {
            object[] results = this.Invoke("DesEncriptar", new object[] {
                        p_Cadena,
                        p_Opc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DesEncriptarAsync(string p_Cadena, int p_Opc) {
            this.DesEncriptarAsync(p_Cadena, p_Opc, null);
        }
        
        /// <remarks/>
        public void DesEncriptarAsync(string p_Cadena, int p_Opc, object userState) {
            if ((this.DesEncriptarOperationCompleted == null)) {
                this.DesEncriptarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDesEncriptarOperationCompleted);
            }
            this.InvokeAsync("DesEncriptar", new object[] {
                        p_Cadena,
                        p_Opc}, this.DesEncriptarOperationCompleted, userState);
        }
        
        private void OnDesEncriptarOperationCompleted(object arg) {
            if ((this.DesEncriptarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DesEncriptarCompleted(this, new DesEncriptarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/descripcionGrupo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string descripcionGrupo(int pGrupo) {
            object[] results = this.Invoke("descripcionGrupo", new object[] {
                        pGrupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void descripcionGrupoAsync(int pGrupo) {
            this.descripcionGrupoAsync(pGrupo, null);
        }
        
        /// <remarks/>
        public void descripcionGrupoAsync(int pGrupo, object userState) {
            if ((this.descripcionGrupoOperationCompleted == null)) {
                this.descripcionGrupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescripcionGrupoOperationCompleted);
            }
            this.InvokeAsync("descripcionGrupo", new object[] {
                        pGrupo}, this.descripcionGrupoOperationCompleted, userState);
        }
        
        private void OndescripcionGrupoOperationCompleted(object arg) {
            if ((this.descripcionGrupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.descripcionGrupoCompleted(this, new descripcionGrupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/descripcionEmpresa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string descripcionEmpresa(int pEmpid, int pGrupo) {
            object[] results = this.Invoke("descripcionEmpresa", new object[] {
                        pEmpid,
                        pGrupo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void descripcionEmpresaAsync(int pEmpid, int pGrupo) {
            this.descripcionEmpresaAsync(pEmpid, pGrupo, null);
        }
        
        /// <remarks/>
        public void descripcionEmpresaAsync(int pEmpid, int pGrupo, object userState) {
            if ((this.descripcionEmpresaOperationCompleted == null)) {
                this.descripcionEmpresaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescripcionEmpresaOperationCompleted);
            }
            this.InvokeAsync("descripcionEmpresa", new object[] {
                        pEmpid,
                        pGrupo}, this.descripcionEmpresaOperationCompleted, userState);
        }
        
        private void OndescripcionEmpresaOperationCompleted(object arg) {
            if ((this.descripcionEmpresaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.descripcionEmpresaCompleted(this, new descripcionEmpresaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/descripcionAgencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string descripcionAgencia(int pEmpid, int pGrupo, string pAgencia) {
            object[] results = this.Invoke("descripcionAgencia", new object[] {
                        pEmpid,
                        pGrupo,
                        pAgencia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void descripcionAgenciaAsync(int pEmpid, int pGrupo, string pAgencia) {
            this.descripcionAgenciaAsync(pEmpid, pGrupo, pAgencia, null);
        }
        
        /// <remarks/>
        public void descripcionAgenciaAsync(int pEmpid, int pGrupo, string pAgencia, object userState) {
            if ((this.descripcionAgenciaOperationCompleted == null)) {
                this.descripcionAgenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OndescripcionAgenciaOperationCompleted);
            }
            this.InvokeAsync("descripcionAgencia", new object[] {
                        pEmpid,
                        pGrupo,
                        pAgencia}, this.descripcionAgenciaOperationCompleted, userState);
        }
        
        private void OndescripcionAgenciaOperationCompleted(object arg) {
            if ((this.descripcionAgenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.descripcionAgenciaCompleted(this, new descripcionAgenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OlvidoContrasena", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void OlvidoContrasena(string pUsrmb) {
            this.Invoke("OlvidoContrasena", new object[] {
                        pUsrmb});
        }
        
        /// <remarks/>
        public void OlvidoContrasenaAsync(string pUsrmb) {
            this.OlvidoContrasenaAsync(pUsrmb, null);
        }
        
        /// <remarks/>
        public void OlvidoContrasenaAsync(string pUsrmb, object userState) {
            if ((this.OlvidoContrasenaOperationCompleted == null)) {
                this.OlvidoContrasenaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOlvidoContrasenaOperationCompleted);
            }
            this.InvokeAsync("OlvidoContrasena", new object[] {
                        pUsrmb}, this.OlvidoContrasenaOperationCompleted, userState);
        }
        
        private void OnOlvidoContrasenaOperationCompleted(object arg) {
            if ((this.OlvidoContrasenaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OlvidoContrasenaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CambioContrasena", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CambioContrasena(int pUsrid, string pContrasena) {
            this.Invoke("CambioContrasena", new object[] {
                        pUsrid,
                        pContrasena});
        }
        
        /// <remarks/>
        public void CambioContrasenaAsync(int pUsrid, string pContrasena) {
            this.CambioContrasenaAsync(pUsrid, pContrasena, null);
        }
        
        /// <remarks/>
        public void CambioContrasenaAsync(int pUsrid, string pContrasena, object userState) {
            if ((this.CambioContrasenaOperationCompleted == null)) {
                this.CambioContrasenaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCambioContrasenaOperationCompleted);
            }
            this.InvokeAsync("CambioContrasena", new object[] {
                        pUsrid,
                        pContrasena}, this.CambioContrasenaOperationCompleted, userState);
        }
        
        private void OnCambioContrasenaOperationCompleted(object arg) {
            if ((this.CambioContrasenaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CambioContrasenaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarMaestraCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarMaestraCorreos(int p_IdCorreo, string pDescCorreo, string pOrigenDatos, int pGrupo, int pEmpid, decimal pPeriodo) {
            this.Invoke("InsertarMaestraCorreos", new object[] {
                        p_IdCorreo,
                        pDescCorreo,
                        pOrigenDatos,
                        pGrupo,
                        pEmpid,
                        pPeriodo});
        }
        
        /// <remarks/>
        public void InsertarMaestraCorreosAsync(int p_IdCorreo, string pDescCorreo, string pOrigenDatos, int pGrupo, int pEmpid, decimal pPeriodo) {
            this.InsertarMaestraCorreosAsync(p_IdCorreo, pDescCorreo, pOrigenDatos, pGrupo, pEmpid, pPeriodo, null);
        }
        
        /// <remarks/>
        public void InsertarMaestraCorreosAsync(int p_IdCorreo, string pDescCorreo, string pOrigenDatos, int pGrupo, int pEmpid, decimal pPeriodo, object userState) {
            if ((this.InsertarMaestraCorreosOperationCompleted == null)) {
                this.InsertarMaestraCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarMaestraCorreosOperationCompleted);
            }
            this.InvokeAsync("InsertarMaestraCorreos", new object[] {
                        p_IdCorreo,
                        pDescCorreo,
                        pOrigenDatos,
                        pGrupo,
                        pEmpid,
                        pPeriodo}, this.InsertarMaestraCorreosOperationCompleted, userState);
        }
        
        private void OnInsertarMaestraCorreosOperationCompleted(object arg) {
            if ((this.InsertarMaestraCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarMaestraCorreosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarMaestraCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarMaestraCorreos(int p_IdCorreo, string pDescCorreo, string pOrigenDatos, int pGrupo, int pEmpid, decimal pPeriodo, int pActivo) {
            this.Invoke("ModificarMaestraCorreos", new object[] {
                        p_IdCorreo,
                        pDescCorreo,
                        pOrigenDatos,
                        pGrupo,
                        pEmpid,
                        pPeriodo,
                        pActivo});
        }
        
        /// <remarks/>
        public void ModificarMaestraCorreosAsync(int p_IdCorreo, string pDescCorreo, string pOrigenDatos, int pGrupo, int pEmpid, decimal pPeriodo, int pActivo) {
            this.ModificarMaestraCorreosAsync(p_IdCorreo, pDescCorreo, pOrigenDatos, pGrupo, pEmpid, pPeriodo, pActivo, null);
        }
        
        /// <remarks/>
        public void ModificarMaestraCorreosAsync(int p_IdCorreo, string pDescCorreo, string pOrigenDatos, int pGrupo, int pEmpid, decimal pPeriodo, int pActivo, object userState) {
            if ((this.ModificarMaestraCorreosOperationCompleted == null)) {
                this.ModificarMaestraCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarMaestraCorreosOperationCompleted);
            }
            this.InvokeAsync("ModificarMaestraCorreos", new object[] {
                        p_IdCorreo,
                        pDescCorreo,
                        pOrigenDatos,
                        pGrupo,
                        pEmpid,
                        pPeriodo,
                        pActivo}, this.ModificarMaestraCorreosOperationCompleted, userState);
        }
        
        private void OnModificarMaestraCorreosOperationCompleted(object arg) {
            if ((this.ModificarMaestraCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarMaestraCorreosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarMaestraCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarMaestraCorreos(int p_IdCorreo) {
            this.Invoke("EliminarMaestraCorreos", new object[] {
                        p_IdCorreo});
        }
        
        /// <remarks/>
        public void EliminarMaestraCorreosAsync(int p_IdCorreo) {
            this.EliminarMaestraCorreosAsync(p_IdCorreo, null);
        }
        
        /// <remarks/>
        public void EliminarMaestraCorreosAsync(int p_IdCorreo, object userState) {
            if ((this.EliminarMaestraCorreosOperationCompleted == null)) {
                this.EliminarMaestraCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarMaestraCorreosOperationCompleted);
            }
            this.InvokeAsync("EliminarMaestraCorreos", new object[] {
                        p_IdCorreo}, this.EliminarMaestraCorreosOperationCompleted, userState);
        }
        
        private void OnEliminarMaestraCorreosOperationCompleted(object arg) {
            if ((this.EliminarMaestraCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarMaestraCorreosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarDetalleCorreos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EliminarDetalleCorreos(int p_IdCorreo, int pIdParametro) {
            this.Invoke("EliminarDetalleCorreos", new object[] {
                        p_IdCorreo,
                        pIdParametro});
        }
        
        /// <remarks/>
        public void EliminarDetalleCorreosAsync(int p_IdCorreo, int pIdParametro) {
            this.EliminarDetalleCorreosAsync(p_IdCorreo, pIdParametro, null);
        }
        
        /// <remarks/>
        public void EliminarDetalleCorreosAsync(int p_IdCorreo, int pIdParametro, object userState) {
            if ((this.EliminarDetalleCorreosOperationCompleted == null)) {
                this.EliminarDetalleCorreosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDetalleCorreosOperationCompleted);
            }
            this.InvokeAsync("EliminarDetalleCorreos", new object[] {
                        p_IdCorreo,
                        pIdParametro}, this.EliminarDetalleCorreosOperationCompleted, userState);
        }
        
        private void OnEliminarDetalleCorreosOperationCompleted(object arg) {
            if ((this.EliminarDetalleCorreosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDetalleCorreosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarDetalleCorreo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void InsertarDetalleCorreo(int pIdCorreo, int pGrupo, int pEmpid, int pIdParametro, int pIdDetalle, string pNmbDetalle, string pValor, string pCampo) {
            this.Invoke("InsertarDetalleCorreo", new object[] {
                        pIdCorreo,
                        pGrupo,
                        pEmpid,
                        pIdParametro,
                        pIdDetalle,
                        pNmbDetalle,
                        pValor,
                        pCampo});
        }
        
        /// <remarks/>
        public void InsertarDetalleCorreoAsync(int pIdCorreo, int pGrupo, int pEmpid, int pIdParametro, int pIdDetalle, string pNmbDetalle, string pValor, string pCampo) {
            this.InsertarDetalleCorreoAsync(pIdCorreo, pGrupo, pEmpid, pIdParametro, pIdDetalle, pNmbDetalle, pValor, pCampo, null);
        }
        
        /// <remarks/>
        public void InsertarDetalleCorreoAsync(int pIdCorreo, int pGrupo, int pEmpid, int pIdParametro, int pIdDetalle, string pNmbDetalle, string pValor, string pCampo, object userState) {
            if ((this.InsertarDetalleCorreoOperationCompleted == null)) {
                this.InsertarDetalleCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarDetalleCorreoOperationCompleted);
            }
            this.InvokeAsync("InsertarDetalleCorreo", new object[] {
                        pIdCorreo,
                        pGrupo,
                        pEmpid,
                        pIdParametro,
                        pIdDetalle,
                        pNmbDetalle,
                        pValor,
                        pCampo}, this.InsertarDetalleCorreoOperationCompleted, userState);
        }
        
        private void OnInsertarDetalleCorreoOperationCompleted(object arg) {
            if ((this.InsertarDetalleCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarDetalleCorreoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/valorCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string valorCache(string p_Pais, string p_Comp, string p_Valor) {
            object[] results = this.Invoke("valorCache", new object[] {
                        p_Pais,
                        p_Comp,
                        p_Valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void valorCacheAsync(string p_Pais, string p_Comp, string p_Valor) {
            this.valorCacheAsync(p_Pais, p_Comp, p_Valor, null);
        }
        
        /// <remarks/>
        public void valorCacheAsync(string p_Pais, string p_Comp, string p_Valor, object userState) {
            if ((this.valorCacheOperationCompleted == null)) {
                this.valorCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalorCacheOperationCompleted);
            }
            this.InvokeAsync("valorCache", new object[] {
                        p_Pais,
                        p_Comp,
                        p_Valor}, this.valorCacheOperationCompleted, userState);
        }
        
        private void OnvalorCacheOperationCompleted(object arg) {
            if ((this.valorCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.valorCacheCompleted(this, new valorCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pais", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Pais() {
            object[] results = this.Invoke("Pais", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PaisAsync() {
            this.PaisAsync(null);
        }
        
        /// <remarks/>
        public void PaisAsync(object userState) {
            if ((this.PaisOperationCompleted == null)) {
                this.PaisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaisOperationCompleted);
            }
            this.InvokeAsync("Pais", new object[0], this.PaisOperationCompleted, userState);
        }
        
        private void OnPaisOperationCompleted(object arg) {
            if ((this.PaisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaisCompleted(this, new PaisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void AgenciasUsuarioCompletedEventHandler(object sender, AgenciasUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgenciasUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgenciasUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EmpresasUsuarioCompletedEventHandler(object sender, EmpresasUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmpresasUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmpresasUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GruposUsuarioCompletedEventHandler(object sender, GruposUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GruposUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GruposUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DivisionesUsuarioCompletedEventHandler(object sender, DivisionesUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DivisionesUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DivisionesUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModulosUsuarioCompletedEventHandler(object sender, ModulosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModulosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModulosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void BaseEmpresaCompletedEventHandler(object sender, BaseEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BaseEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BaseEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void datosUsuarioCompletedEventHandler(object sender, datosUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class datosUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal datosUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void usuarioFuncionCompletedEventHandler(object sender, usuarioFuncionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class usuarioFuncionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal usuarioFuncionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void usuarioValidoCompletedEventHandler(object sender, usuarioValidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class usuarioValidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal usuarioValidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MaestraCorreosCompletedEventHandler(object sender, MaestraCorreosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestraCorreosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestraCorreosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MaestraCorreosGeneralCompletedEventHandler(object sender, MaestraCorreosGeneralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MaestraCorreosGeneralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MaestraCorreosGeneralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ParametrosEncCorreosCompletedEventHandler(object sender, ParametrosEncCorreosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametrosEncCorreosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParametrosEncCorreosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ParametrosDetCorreosCompletedEventHandler(object sender, ParametrosDetCorreosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParametrosDetCorreosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParametrosDetCorreosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void valorParametrosDetCorreosCompletedEventHandler(object sender, valorParametrosDetCorreosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class valorParametrosDetCorreosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal valorParametrosDetCorreosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DatosCorreoCompletedEventHandler(object sender, DatosCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DatosCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DatosCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ejecutaProcedimientoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EncriptarCompletedEventHandler(object sender, EncriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void DesEncriptarCompletedEventHandler(object sender, DesEncriptarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DesEncriptarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DesEncriptarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void descripcionGrupoCompletedEventHandler(object sender, descripcionGrupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class descripcionGrupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal descripcionGrupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void descripcionEmpresaCompletedEventHandler(object sender, descripcionEmpresaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class descripcionEmpresaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal descripcionEmpresaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void descripcionAgenciaCompletedEventHandler(object sender, descripcionAgenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class descripcionAgenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal descripcionAgenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void OlvidoContrasenaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CambioContrasenaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarMaestraCorreosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ModificarMaestraCorreosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarMaestraCorreosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EliminarDetalleCorreosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void InsertarDetalleCorreoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void valorCacheCompletedEventHandler(object sender, valorCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class valorCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal valorCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void PaisCompletedEventHandler(object sender, PaisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591