//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.269
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsServiceSalesOrder.ServicioSalesOrder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clsResponse", Namespace="http://www.praxair.com.co/SalesOrder")]
    [System.SerializableAttribute()]
    public partial class clsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeDescField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDesc {
            get {
                return this.MessageDescField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDescField, value) != true)) {
                    this.MessageDescField = value;
                    this.RaisePropertyChanged("MessageDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeDesc {
            get {
                return this.TypeDescField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeDescField, value) != true)) {
                    this.TypeDescField = value;
                    this.RaisePropertyChanged("TypeDesc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.praxair.com.co/SalesOrder", ConfigurationName="ServicioSalesOrder.IWS_SalesOrder")]
    public interface IWS_SalesOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/GetSalesOrder", ReplyAction="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/GetSalesOrderResponse")]
        void GetSalesOrder(string InterfaceStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/Confirmation", ReplyAction="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/ConfirmationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WindowsServiceSalesOrder.ServicioSalesOrder.clsResponse), Action="http://www.praxair.com.co/SalesOrder/IWS_SalesOrder/ConfirmationInternalException" +
            "", Name="InternalException")]
        WindowsServiceSalesOrder.ServicioSalesOrder.clsResponse[] Confirmation(string mcu, string legacyConsecutive, string legacyPrefix, string dcto, string interfaceStatus);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWS_SalesOrderChannel : WindowsServiceSalesOrder.ServicioSalesOrder.IWS_SalesOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SalesOrderClient : System.ServiceModel.ClientBase<WindowsServiceSalesOrder.ServicioSalesOrder.IWS_SalesOrder>, WindowsServiceSalesOrder.ServicioSalesOrder.IWS_SalesOrder {
        
        public WS_SalesOrderClient() {
        }
        
        public WS_SalesOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SalesOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SalesOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SalesOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetSalesOrder(string InterfaceStatus) {
            base.Channel.GetSalesOrder(InterfaceStatus);
        }
        
        public WindowsServiceSalesOrder.ServicioSalesOrder.clsResponse[] Confirmation(string mcu, string legacyConsecutive, string legacyPrefix, string dcto, string interfaceStatus) {
            return base.Channel.Confirmation(mcu, legacyConsecutive, legacyPrefix, dcto, interfaceStatus);
        }
    }
}
